// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App Wails 应用主结构体（所有公开方法均可被前端直接调用）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddBet 新增一条投注记录
 */
export function AddBet(bet: models$0.Bet): $CancellablePromise<number> {
    return $Call.ByID(2227335755, bet);
}

/**
 * CalculateKelly 凯利公式计算（前端 AI 沙盒调用）
 */
export function CalculateKelly(params: models$0.KellyParams): $CancellablePromise<models$0.KellyResult> {
    return $Call.ByID(1302672670, params).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetAPIQuotaStatus 获取 API 配额使用状态
 */
export function GetAPIQuotaStatus(): $CancellablePromise<$models.APIQuotaStatus> {
    return $Call.ByID(4065142205).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetActiveLeague 获取当前活跃联赛的 sportKey
 */
export function GetActiveLeague(): $CancellablePromise<string> {
    return $Call.ByID(1286217156);
}

/**
 * GetBetSummary 获取账本汇总统计
 */
export function GetBetSummary(): $CancellablePromise<models$0.BetSummary> {
    return $Call.ByID(964925378).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetBets 获取所有投注记录
 */
export function GetBets(): $CancellablePromise<models$0.Bet[]> {
    return $Call.ByID(1357610255).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetLLMAnalysis 获取指定比赛的大模型深度量化预测报告
 */
export function GetLLMAnalysis(matchID: string, oddsHome: number, oddsDraw: number, oddsAway: number): $CancellablePromise<string> {
    return $Call.ByID(1682156196, matchID, oddsHome, oddsDraw, oddsAway);
}

/**
 * GetLeagues 获取所有支持的联赛列表（前端初始化联赛选择器时调用）
 */
export function GetLeagues(): $CancellablePromise<models$0.League[]> {
    return $Call.ByID(3587370431).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetMatches 获取所有比赛列表（前端启动时调用，获取初始数据）
 */
export function GetMatches(): $CancellablePromise<models$0.Match[]> {
    return $Call.ByID(3255011868).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetMatchesByLeague 按联赛名称过滤获取比赛
 */
export function GetMatchesByLeague(league: string): $CancellablePromise<models$0.Match[]> {
    return $Call.ByID(3796927484, league).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetOddsHistory 获取某场比赛的历史赔率（最近100条）
 */
export function GetOddsHistory(matchID: string): $CancellablePromise<models$0.OddsSnapshot[]> {
    return $Call.ByID(3862188275, matchID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * SetActiveLeague 切换当前监控的联赛（前端联赛选择器调用）
 * 会同时切换赔率服务和比赛服务的目标联赛
 */
export function SetActiveLeague(sportKey: string): $CancellablePromise<void> {
    return $Call.ByID(239293344, sportKey);
}

/**
 * StartPolling 手动启动轮询（前端控制）
 */
export function StartPolling(): $CancellablePromise<void> {
    return $Call.ByID(2487729474);
}

/**
 * StopPolling 手动停止轮询（前端控制）
 */
export function StopPolling(): $CancellablePromise<void> {
    return $Call.ByID(3487326408);
}

/**
 * UpdateBetResult 结算投注
 */
export function UpdateBetResult(betID: number, result: string, pnl: number): $CancellablePromise<void> {
    return $Call.ByID(3428234322, betID, result, pnl);
}

// Private type creation functions
const $$createType0 = models$0.KellyResult.createFrom;
const $$createType1 = $models.APIQuotaStatus.createFrom;
const $$createType2 = models$0.BetSummary.createFrom;
const $$createType3 = models$0.Bet.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = models$0.League.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = models$0.Match.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = models$0.OddsSnapshot.createFrom;
const $$createType10 = $Create.Array($$createType9);
