// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * APIQuotaStatus API 配额状态（前端展示用）
 */
export class APIQuotaStatus {
    /**
     * The Odds API 使用描述
     */
    "oddsUsed": string;

    /**
     * API-Football 今日已用次数
     */
    "matchUsed": number;

    /**
     * API-Football 每日限额
     */
    "matchLimit": number;

    /**
     * API-Football 今日剩余
     */
    "matchRemain": number;

    /** Creates a new APIQuotaStatus instance. */
    constructor($$source: Partial<APIQuotaStatus> = {}) {
        if (!("oddsUsed" in $$source)) {
            this["oddsUsed"] = "";
        }
        if (!("matchUsed" in $$source)) {
            this["matchUsed"] = 0;
        }
        if (!("matchLimit" in $$source)) {
            this["matchLimit"] = 0;
        }
        if (!("matchRemain" in $$source)) {
            this["matchRemain"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIQuotaStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): APIQuotaStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIQuotaStatus($$parsedSource as Partial<APIQuotaStatus>);
    }
}
