// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Bet 单条投注记录（账本条目）
 */
export class Bet {
    "id": number;
    "matchId": string;
    "homeTeam": string;
    "awayTeam": string;
    "bookmaker": string;
    "market": string;
    "outcome": string;
    "odds": number;
    "stake": number;
    "result": BetResult;

    /**
     * 盈亏金额
     */
    "pnl": number;

    /**
     * 下注时的凯利分数
     */
    "kellyFraction": number;
    "placedAt": time$0.Time;
    "settledAt"?: time$0.Time | null;
    "notes": string;

    /** Creates a new Bet instance. */
    constructor($$source: Partial<Bet> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("matchId" in $$source)) {
            this["matchId"] = "";
        }
        if (!("homeTeam" in $$source)) {
            this["homeTeam"] = "";
        }
        if (!("awayTeam" in $$source)) {
            this["awayTeam"] = "";
        }
        if (!("bookmaker" in $$source)) {
            this["bookmaker"] = "";
        }
        if (!("market" in $$source)) {
            this["market"] = "";
        }
        if (!("outcome" in $$source)) {
            this["outcome"] = "";
        }
        if (!("odds" in $$source)) {
            this["odds"] = 0;
        }
        if (!("stake" in $$source)) {
            this["stake"] = 0;
        }
        if (!("result" in $$source)) {
            this["result"] = BetResult.$zero;
        }
        if (!("pnl" in $$source)) {
            this["pnl"] = 0;
        }
        if (!("kellyFraction" in $$source)) {
            this["kellyFraction"] = 0;
        }
        if (!("placedAt" in $$source)) {
            this["placedAt"] = null;
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Bet instance from a string or object.
     */
    static createFrom($$source: any = {}): Bet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Bet($$parsedSource as Partial<Bet>);
    }
}

/**
 * BetResult 投注结果枚举
 */
export enum BetResult {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BetWin = "WIN",
    BetLoss = "LOSS",
    BetDraw = "DRAW",
    BetVoid = "VOID",
    BetPending = "PENDING",
};

/**
 * BetSummary 账本汇总统计（Reports 页面展示）
 */
export class BetSummary {
    "totalBets": number;
    "winCount": number;
    "lossCount": number;
    "winRate": number;
    "totalStake": number;
    "totalPnl": number;
    "roi": number;
    "avgOdds": number;
    "maxDrawdown": number;

    /** Creates a new BetSummary instance. */
    constructor($$source: Partial<BetSummary> = {}) {
        if (!("totalBets" in $$source)) {
            this["totalBets"] = 0;
        }
        if (!("winCount" in $$source)) {
            this["winCount"] = 0;
        }
        if (!("lossCount" in $$source)) {
            this["lossCount"] = 0;
        }
        if (!("winRate" in $$source)) {
            this["winRate"] = 0;
        }
        if (!("totalStake" in $$source)) {
            this["totalStake"] = 0;
        }
        if (!("totalPnl" in $$source)) {
            this["totalPnl"] = 0;
        }
        if (!("roi" in $$source)) {
            this["roi"] = 0;
        }
        if (!("avgOdds" in $$source)) {
            this["avgOdds"] = 0;
        }
        if (!("maxDrawdown" in $$source)) {
            this["maxDrawdown"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BetSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): BetSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BetSummary($$parsedSource as Partial<BetSummary>);
    }
}

/**
 * BookmakerOdds 某博彩平台对某场比赛某盘口的报价
 */
export class BookmakerOdds {
    /**
     * "Bet365" / "Pinnacle" / "William Hill"
     */
    "bookmaker": string;
    "market": MarketType;
    "outcomes": OddsOutcome[];
    "updatedAt": time$0.Time;

    /** Creates a new BookmakerOdds instance. */
    constructor($$source: Partial<BookmakerOdds> = {}) {
        if (!("bookmaker" in $$source)) {
            this["bookmaker"] = "";
        }
        if (!("market" in $$source)) {
            this["market"] = MarketType.$zero;
        }
        if (!("outcomes" in $$source)) {
            this["outcomes"] = [];
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BookmakerOdds instance from a string or object.
     */
    static createFrom($$source: any = {}): BookmakerOdds {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("outcomes" in $$parsedSource) {
            $$parsedSource["outcomes"] = $$createField2_0($$parsedSource["outcomes"]);
        }
        return new BookmakerOdds($$parsedSource as Partial<BookmakerOdds>);
    }
}

/**
 * KellyParams 凯利公式前端传入参数
 */
export class KellyParams {
    /**
     * 博彩平台赔率（小数格式）
     */
    "odds": number;

    /**
     * 估计胜率（0~1）
     */
    "winProb": number;

    /**
     * 当前总资金
     */
    "bankroll": number;

    /**
     * 凯利分数（通常 0.25~0.5，避免过激）
     */
    "fraction": number;
    "weights": PredictionWeights;

    /** Creates a new KellyParams instance. */
    constructor($$source: Partial<KellyParams> = {}) {
        if (!("odds" in $$source)) {
            this["odds"] = 0;
        }
        if (!("winProb" in $$source)) {
            this["winProb"] = 0;
        }
        if (!("bankroll" in $$source)) {
            this["bankroll"] = 0;
        }
        if (!("fraction" in $$source)) {
            this["fraction"] = 0;
        }
        if (!("weights" in $$source)) {
            this["weights"] = (new PredictionWeights());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KellyParams instance from a string or object.
     */
    static createFrom($$source: any = {}): KellyParams {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("weights" in $$parsedSource) {
            $$parsedSource["weights"] = $$createField4_0($$parsedSource["weights"]);
        }
        return new KellyParams($$parsedSource as Partial<KellyParams>);
    }
}

/**
 * KellyResult 凯利公式计算结果
 */
export class KellyResult {
    /**
     * f* = (b*p - q) / b，其中 b = odds-1, p = winProb, q = 1-winProb
     * 原始凯利分数
     */
    "kellyFraction": number;

    /**
     * 调整后（乘以 fraction 参数）
     */
    "adjustedFraction": number;

    /**
     * 建议投注金额
     */
    "suggestedStake": number;

    /**
     * 期望值 = p*odds - 1
     */
    "expectedValue": number;

    /**
     * 赔率边际 %
     */
    "edgePct": number;

    /** Creates a new KellyResult instance. */
    constructor($$source: Partial<KellyResult> = {}) {
        if (!("kellyFraction" in $$source)) {
            this["kellyFraction"] = 0;
        }
        if (!("adjustedFraction" in $$source)) {
            this["adjustedFraction"] = 0;
        }
        if (!("suggestedStake" in $$source)) {
            this["suggestedStake"] = 0;
        }
        if (!("expectedValue" in $$source)) {
            this["expectedValue"] = 0;
        }
        if (!("edgePct" in $$source)) {
            this["edgePct"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KellyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): KellyResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KellyResult($$parsedSource as Partial<KellyResult>);
    }
}

/**
 * League 联赛元数据（内置注册表条目）
 */
export class League {
    /**
     * The Odds API sport key，如 "soccer_epl"
     */
    "sportKey": string;

    /**
     * 联赛中文名，如 "英超"
     */
    "name": string;

    /**
     * 联赛全名，如 "英格兰足球超级联赛"
     */
    "fullName": string;

    /**
     * 国家/地区
     */
    "country": string;

    /**
     * 联赛图标 emoji
     */
    "emoji": string;

    /**
     * API-Football 中的联赛 ID
     */
    "apiFootballId": number;

    /**
     * 当前赛季年份
     */
    "season": number;

    /**
     * 联赛类型：domestic / cup
     */
    "type": LeagueType;

    /** Creates a new League instance. */
    constructor($$source: Partial<League> = {}) {
        if (!("sportKey" in $$source)) {
            this["sportKey"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("fullName" in $$source)) {
            this["fullName"] = "";
        }
        if (!("country" in $$source)) {
            this["country"] = "";
        }
        if (!("emoji" in $$source)) {
            this["emoji"] = "";
        }
        if (!("apiFootballId" in $$source)) {
            this["apiFootballId"] = 0;
        }
        if (!("season" in $$source)) {
            this["season"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = LeagueType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new League instance from a string or object.
     */
    static createFrom($$source: any = {}): League {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new League($$parsedSource as Partial<League>);
    }
}

/**
 * LeagueType 联赛类型枚举
 */
export enum LeagueType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 联赛制（英超、西甲等，有积分榜）
     */
    LeagueDomestic = "domestic",

    /**
     * 杯赛/锦标赛制（世界杯、欧冠等，有分组+淘汰赛）
     */
    LeagueCup = "cup",
};

/**
 * MarketType 盘口类型枚举
 */
export enum MarketType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 胜平负
     */
    Market1X2 = "h2h",

    /**
     * 让球盘
     */
    MarketHandicap = "spreads",

    /**
     * 大小球
     */
    MarketOverUnder = "totals",
};

/**
 * Match 代表一场足球比赛的基础信息（来自 API-Football 或本地数据库）
 */
export class Match {
    "id": string;
    "homeTeam": string;
    "awayTeam": string;
    "league": string;
    "country": string;
    "scheduledAt": time$0.Time;

    /**
     * "NS"=未开赛 "1H"=上半场 "HT"=中场 "2H"=下半场 "FT"=结束
     */
    "status": string;
    "homeScore": number;
    "awayScore": number;

    /**
     * 当前比赛时间（分钟）
     */
    "minute": number;

    /** Creates a new Match instance. */
    constructor($$source: Partial<Match> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("homeTeam" in $$source)) {
            this["homeTeam"] = "";
        }
        if (!("awayTeam" in $$source)) {
            this["awayTeam"] = "";
        }
        if (!("league" in $$source)) {
            this["league"] = "";
        }
        if (!("country" in $$source)) {
            this["country"] = "";
        }
        if (!("scheduledAt" in $$source)) {
            this["scheduledAt"] = null;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("homeScore" in $$source)) {
            this["homeScore"] = 0;
        }
        if (!("awayScore" in $$source)) {
            this["awayScore"] = 0;
        }
        if (!("minute" in $$source)) {
            this["minute"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Match instance from a string or object.
     */
    static createFrom($$source: any = {}): Match {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Match($$parsedSource as Partial<Match>);
    }
}

/**
 * OddsOutcome 单个赔率结果（某平台某盘口某选项的赔率）
 */
export class OddsOutcome {
    /**
     * "Home" / "Draw" / "Away" / "Over 2.5" 等
     */
    "name": string;

    /**
     * 欧洲赔率（小数格式，如 2.50）
     */
    "price": number;

    /** Creates a new OddsOutcome instance. */
    constructor($$source: Partial<OddsOutcome> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("price" in $$source)) {
            this["price"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OddsOutcome instance from a string or object.
     */
    static createFrom($$source: any = {}): OddsOutcome {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OddsOutcome($$parsedSource as Partial<OddsOutcome>);
    }
}

/**
 * OddsSnapshot 某场比赛在某时刻的全网赔率快照（Wails 事件推送载荷）
 */
export class OddsSnapshot {
    "matchId": string;
    "match": Match;
    "bookmakers": BookmakerOdds[];
    "capturedAt": time$0.Time;

    /** Creates a new OddsSnapshot instance. */
    constructor($$source: Partial<OddsSnapshot> = {}) {
        if (!("matchId" in $$source)) {
            this["matchId"] = "";
        }
        if (!("match" in $$source)) {
            this["match"] = (new Match());
        }
        if (!("bookmakers" in $$source)) {
            this["bookmakers"] = [];
        }
        if (!("capturedAt" in $$source)) {
            this["capturedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OddsSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): OddsSnapshot {
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("match" in $$parsedSource) {
            $$parsedSource["match"] = $$createField1_0($$parsedSource["match"]);
        }
        if ("bookmakers" in $$parsedSource) {
            $$parsedSource["bookmakers"] = $$createField2_0($$parsedSource["bookmakers"]);
        }
        return new OddsSnapshot($$parsedSource as Partial<OddsSnapshot>);
    }
}

/**
 * PredictionWeights AI 预测时各维度权重（前端 Slider 沙盒控制）
 */
export class PredictionWeights {
    /**
     * 近期状态权重 0~1
     */
    "formWeight": number;

    /**
     * 历史交锋权重 0~1
     */
    "h2hWeight": number;

    /**
     * 赔率隐含概率权重 0~1
     */
    "oddsWeight": number;

    /**
     * xG 数据权重 0~1
     */
    "xgWeight": number;

    /**
     * 伤病/阵容权重 0~1
     */
    "injuryWeight": number;

    /** Creates a new PredictionWeights instance. */
    constructor($$source: Partial<PredictionWeights> = {}) {
        if (!("formWeight" in $$source)) {
            this["formWeight"] = 0;
        }
        if (!("h2hWeight" in $$source)) {
            this["h2hWeight"] = 0;
        }
        if (!("oddsWeight" in $$source)) {
            this["oddsWeight"] = 0;
        }
        if (!("xgWeight" in $$source)) {
            this["xgWeight"] = 0;
        }
        if (!("injuryWeight" in $$source)) {
            this["injuryWeight"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PredictionWeights instance from a string or object.
     */
    static createFrom($$source: any = {}): PredictionWeights {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PredictionWeights($$parsedSource as Partial<PredictionWeights>);
    }
}

// Private type creation functions
const $$createType0 = OddsOutcome.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = PredictionWeights.createFrom;
const $$createType3 = Match.createFrom;
const $$createType4 = BookmakerOdds.createFrom;
const $$createType5 = $Create.Array($$createType4);
